### ISSUE TITLE
Adding support for h2o models?

### ISSUE THREAD

**Issue by SixiangHu** [pbiecek/DALEX#8]
Would DALEX is going to support h2o models?

Currently, H2OFrame is not supported when running `single_variable`.

**Comment by pbiecek** [comment]
Right now we are targeting caret and mlr models.
Let's keep h2o models in the short TODO list, thanks!

**Comment by cregouby** [comment]
Hello, 
Let me emphasis the need for amazing DALEX to run specifically on h2o.automl models (usually ensemble models)
Starting with the [Demo Notebook](http://docs.h2o.ai/h2o-tutorials/latest-stable/h2o-world-2017/automl/R/automl_regression_powerplant_output.Rmd), and adding the following DALEX commands
```R
library(DALEX)
explainer<-explain(model=aml@leader,data=test, y=y, predict_function = h2o.predict, label="h2o.automl leaderboard")
varimp_automl<-variable_importance(explainer)
```
the following error
`Error in .h2o.doSafeREST(h2oRestApiVersion = h2oRestApiVersion, urlSuffix = page, : ERROR MESSAGE: H2O does not currently reorder rows, please sort your row selection first`
is raised when passing through 
`sampled_data <- explainer$data[sampled_rows, ]`

**Comment by pbiecek** [comment]
`H2OFrame` behaves differently than `data.frame`,
so some direct casts are needed.

Below is an example how this may be done.  
In future DALEX explainers shall be better in dealing with `H2OFrame` or `xgb.matrix` or other non-data.frames.

```
explainer <- explain(model = aml@leader,
                   data = as.data.frame(test), 
                   y = as.data.frame(test)$HourlyEnergyOutputMW, 
                   predict_function = function(m,x)  {
                     xx <- as.h2o(x)
                     attr(h2o.predict(m, xx), "data")$predict
                   }, 
                   label = "h2o.automl leaderboard")
varimp_automl <- variable_importance(explainer)
```

**Comment by pbiecek** [comment]
@ledell Thanks a lot!!
I'm on H2O workshop and I hope that after it I will better understand H2O architecture.
Happy to chat with you about this during the eRum, will look for you at coffe breaks.

**Comment by pbiecek** [comment]
Alicja has prepared an use-case for H2O models
https://rawgit.com/agosiewska/DALEX_docs/master/vignettes/DALEX_h2o.html

**Comment by dkincaid** [comment]
This is fantastic! Thanks for the very clear example and guide. 

One question I have though is about performance. Everything from the guide runs well over the small dataset. However, when I try to use my dataset and model (4,000 rows by 3,100 columns) it is very, very slow. It's going on 3 hours right now running prediction_breakdown() on a single observation. This is using a GBM model in H2O.

I see it many predict calls to H2O and uploading a different data frame each time. Just wondering if this due to having to pass the H2O data frames back and forth too much or something core to DALEX.

**Comment by pbiecek** [comment]
It is doable, but requires some changes in existing DALEX functions. 
It's high on our TODO list, so some day ... ;-)

**Comment by agosiewska** [comment]
I've added a branch H2O and uploaded there the attempt for adding support for h2o.

However, function `variable_response()` still works slow. This is because calling functions `pdp()` and `ALEPlot()` from other packages. Those functions require data.frame or matrix. So I couldn't avoid passing the H2O data frames back and forth. 
The same problem for `prediction_breakdown()`.

If someone would like to look at the code, it is here: https://github.com/pbiecek/DALEX/tree/H2O
I've added the if statement for functions `variable_response()`, `prediction_breakdown()`, `model_performance()`, and `variable_importance()`. It checks whether the data is an H2OFrame and calls the equivalent function with suffix `h2o`. 
Functions with suffixes are in `h2o_functions.R` file.

Below is an example. Now, there is no need to pass custom predict function to `explainer()`.
```
devtools::install_github("pbiecek/DALEX", ref="H2O")

library(h2o)
library(DALEX)

h2o.init()
apartments_hf <- as.h2o(apartments)
model_h2o_glm <- h2o.glm(y = "m2.price", training_frame = apartments_hf)

explainer_h2o_glm <- explain(model = model_h2o_glm,
                             data = apartments_hf[,2:6],
                             y = apartments_hf$m2.price,
                             label = "h2o glm")

model_performance(explainer_h2o_glm)
variable_importance(explainer_h2o_glm)
variable_response(explainer_h2o_glm, variable = "construction.year", type = "pdp")
variable_response(explainer_h2o_glm, variable = "construction.year", type = "ale")
variable_response(explainer_h2o_glm, variable = "district", type = "factor")
new_apartment <- apartmentsTest_hf[1,]
pb_h2o_glm <- prediction_breakdown(explainer_h2o_glm, observation = new_apartment)
```

**Comment by dkincaid** [comment]
Starting to try this out. Thanks for putting in the work. One quick question though. It looks like you put the h2o package in the "Imports" section of the DESCRIPTION file. This will cause problems for people since it installs the latest h2o package which some may not want. Should we move it to "Suggests"?

**Comment by dkincaid** [comment]
Something weird going on here. `model_performance()` returns a java `ArrayIndexOutOfBoundsException` error from H2O. `variable_importance()` runs for 2 hours and returns nothing:

```
> varimp <- variable_importance(explainer)
> varimp
      variable dropout_loss            label
1 _full_model_          NaN H2OBinomialModel
2   _baseline_          NaN H2OBinomialModel

> plot(varimp)
Warning message:
Removed 2 rows containing missing values (geom_errorbar).
```

**Comment by agosiewska** [comment]
Thank you very much.

I've added h2o to Imports because I'm using functions from h2o to manipulate H2OFrames. This reduces the number of conversions from H2OFrame to data.frame and vice versa.

Could you give an example of a code that is not working? It seems to me that the one I put up above is ok.

**Comment by dkincaid** [comment]
I think adding h2o to Imports though forces the h2o package that's on CRAN to install whenever the DALEX package is installed. I don't think we want to do that since not everyone uses h2o and those of us who do really need to be able to control which version of h2o package is installed at any time. Putting the dependency in Suggests instead of Imports would be more proper I think.

Your example on the apartments data does work. So there is something in my real world data that is making it choke for some reason. Once I get this project done that I'm working on right now I will take a closer look and try to put together a reproducible example.

Thanks again for your work on this. It is a big step in the right direction.

**Comment by pbiecek** [comment]
I think that the DALEX on CRAN will stay as it is in the branch master, without h2o dependency
We will keep h2o version of DALEX in the H2O branch for now.

**Comment by dkincaid** [comment]
Understood, but I think at some point you'll want to merge it into master rather than trying to maintain two different versions of the package. I strongly advise moving that dependency into Suggests instead of Imports. If you look at other packages like `caret` which sometimes use other packages you see that those packages are in the Suggests section of DESCRIPTION for this very reason. It gives the users of the package better control over their local environments.

**Comment by ledell** [comment]
New blog post about using DALEX with h2o models: http://www.business-science.io/business/2018/07/23/dalex-feature-interpretation.html

**Comment by pbiecek** [comment]
Szymon has just added wrappers for h2o models to the yhat 
https://github.com/pbiecek/DALEX/blob/master/R/yhat.R#L160

and prepared an example how to compare models across languages https://raw.githack.com/pbiecek/DALEX_docs/master/vignettes/Multilanguages_comparision.html

It is not the most efficient approach as it requires data transfer to R, 
but we need to wait for the more universal interface between objects in different languages (I will look closely at Ursa Labs)
